### PR TITLE
Merge in paper.md and functioning tests

### PR DESCRIPTION
**Pull request by Islast**
- [x] I'm ready to merge

* **What's the context for this pull request?** 
_(this is a good place to reference any issues that this PR addresses)_
For a long time we have suspended testing on the whitakerlab master branch due to the intractability of the errors in our test suite. Since I am noticing more activity around this project lately, I am resuming testing but ignoring the regression tests, which I still haven't fixed.

* **What's new?**
updates to a lot of the tests; updates to `.travis.yml`
There are also some updates to the nilearn plotting methods

* **What should a reviewer feedback on?**
The testing suite (minus the regression tests) should run smoothly in Travis

* **Does anything need to be updated after merge?** 
_(e.g the wiki or the WhitakerLab website)_

Ultimately it would be nice to merge all this in to master.

### CODE REVIEW

**Comment by KirstieJane** [comment]
WOOOHOOO - Thanks @Islast!

**Comment by KirstieJane** [comment]
(and PR #100! Nicely timed!)

**Comment by KirstieJane** [comment]
Oh - I'm confused. This was just to `dev` branch? Not to `master`?

Any use in merging it into master @Islast? What do you think?

**Comment by Islast** [comment]
We can definitely merge into master, I might wait until #101 is merged in, just in case we cause conflicts

**Comment by wingedRuslan** [comment]
I have just merged into master, so feel free to merge your changes. Please let me know if there will appear any conflicts or issues :)

**Pull request merged**
