### PR TITLE
Fix deprecation warnings

### PR DESCRIPTION
**Pull request by souravsingh**
Fixes a part of #67 by replacing `tsplot()` with `lineplot()` and `as_matrix` with `values`.

### CODE REVIEW

**Comment by souravsingh** [comment]
Sure, let me add a few commits to fix the comments

**Comment by souravsingh** [comment]
@KirstieJane I have made the changes to the requirements file. Should I go ahead and mae a separate PR for the example?

**Comment by souravsingh** [comment]
@Islast Is this ready to merge?

**Comment by Islast** [comment]
apologies @souravsingh I have been on holiday for a few days. Yes this looks good to merge.

**Pull request merged**
