### PR TITLE
Add Nilearn plotting functionality to scona

### PR DESCRIPTION
**Pull request by wingedRuslan**
- [x] I'm ready to merge

* **What's the context for this pull request?** 
_(this is a good place to reference any issues that this PR addresses)_

* **What's new?**  
Created visualisation tools for plotting with nilearn
Added tutorial to show how to use these tools

* **What should a reviewer feedback on?**  
Functions Implementation
Produced plots

* **Does anything need to be updated after merge?** 
_(e.g the wiki or the WhitakerLab website)_

### CODE REVIEW

**Comment by Islast** [comment]
[compare this branch to Ruslan/master (eg PR 121)](https://github.com/wingedRuslan/scona/compare/master...wingedRuslan:nilearn_plotting?expand=1)

**Comment by KirstieJane** [comment]
Hey @wingedRuslan!

Can we adjust the `view_connectome` code so that the symmetric colormap works more intuitively? If the threshold is positive can we create a copy of the graph that sets all negative weights to 0 so we don't have to deal with them?

```
G_pos = G.copy()

for edge in G_pos.edges():
    if G.edges[edge]['weight'] < 0.0:
        G.edges[edge]['weight'] = 0
```

OR you can just do it from the adjacency matrix as that's what's passed to `plotting.view_connectome`.

The only slightly fiddly bit is figuring out the threshold - if its a number which is greater than 0 then that's easy, but if it is a percentage as a string you need to detect that its a string, drop the '%' character and then divide by 100 before you pass to `np.percentile`.

Does that make sense?

**Comment by KirstieJane** [comment]
Hey @wingedRuslan - I'd love to get this merged in so that it can be in your final report! Can you fix the merge conflicts and ping me in gitter when you think the tutorials is good to be merged? I think its _very_ close and so I'll try to find time either before or after the meeting to review.

**Comment by wingedRuslan** [comment]
@KirstieJane, sure, I plan to do this today! It would be great if you would have time after the meeting to review.

**Pull request merged**
